name: hello_world
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-slim
    name: greeting the user
    steps:
      - run: echo "Hello World"
      - run: echo "hacker=Harish" >> GITHUB_OUTPUT
        id: alpas1
      - run: echo "the hacker is $hacker"
        id: alpas2
  job2:
    needs: job1
    runs-on: ubuntu-slim
    name: greet user using python
    steps:
      - run: print("hello world")
        shell: python
